---
name: "pre-release"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Release
        run: pwd && ls && chmod 755 scripts/release.sh && ./scripts/release.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            release/sensei-0.2.8-amd64.tar.gz
