---
name: "pre-release"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
#   tags:
#     - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo $(pwd) && echo $(ls) && chmod 755 scripts/release.sh && ./scripts/release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/sensei-0.2.8-amd64.tar.gz
