---
name: "pre-release"

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cd scripts && chmod 755 release.sh && ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/sensei-0.2.8-amd64.tar.gz
            LICENSE
            README.md
